# Generated by Django 5.0.1 on 2025-08-26 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('webservice_name', models.CharField(max_length=100)),
                ('webservice_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('email_alert', models.BooleanField(default=True)),
                ('monitor_interval', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('expect_status_code', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webstatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ping', models.IntegerField()),
                ('status', models.BooleanField()),
                ('status_code', models.IntegerField()),
                ('datendtime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.webservice')),
            ],
        ),
    ]
