# Generated by Django 4.2 on 2025-08-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webstatus',
            old_name='datendtime',
            new_name='date_and_time',
        ),
    ]
